Attribute VB_Name = "vw_strings"

' user cell strings
Public Const S_TYPE as String = "Type"
Public Const S_CHILDOFFSET as String = "ChildOffset"
Public Const S_BUSWIDTH as String = "BusWidth"
Public Const S_SKEWWIDTH as String = "SkewWidth"
Public Const S_EDGES as String = "Edges"
Public Const S_ACTIVEWIDTH as String = "ActiveWidth"
Public Const S_PULSES as String = "Pulses"
Public Const S_TEST as String = "Test"
Public Const S_PARENT as String = "Parent"

' data cell strings
Public Const S_NAME as String = "Name"
Public Const S_CLOCK as String = "Clock"
Public Const S_SIGNAL as String = "Signal"
Public Const S_ACTIVELOW as String = "ActiveLow"
Public Const S_PERIOD as String = "Period"
Public Const S_SKEW as String = "Skew"
Public Const S_DELAY as String = "Delay"
Public Const S_DUTYCYCLE as String = "DutyCycle"
Public Const S_SIGNALSKEW as String = "SignalSkew"
Public Const S_EVENTTYPE as String = "EventType"
Public Const S_EVENTTRIGGER as String = "EventTrigger"
Public Const S_EVENTPOSITION as String = "EventPosition"
Public Const S_LABELEDGES as String = "LabelEdges"
Public Const S_LABELSIZE as String = "LabelSize"
Public Const S_LABELFONT as String = "LabelFont"

' data cell labels
Public Const S_LABEL_ACTIVELOW as String = """Active Low"""
Public Const S_LABEL_SKEW as String = """Skew %"""
Public Const S_LABEL_DUTYCYCLE as String = """Duty Cycle %"""
Public Const S_LABEL_SIGNALSKEW as String = """Signal Skew"""
Public Const S_LABEL_EVENTTYPE as String = """Event Type"""
Public Const S_LABEL_EVENTTRIGGER as String = """Trigger"""
Public Const S_LABEL_EVENTPOSITION as String = """Position"""
Public Const S_LABEL_LABELEDGES as String = """Label Edges"""
Public Const S_LABEL_LABELSIZE as String = """Label Size"""
Public Const S_LABEL_LABELFONT as String = """Label Font Pt"""

' label shape strings
Public Const S_LBL_RECTANGLE as String = "Rectangle"
Public Const S_LBL_SQUARE as String = "Square"
Public Const S_LBL_DIAMOND as String = "Diamond"
Public Const S_LBL_RND_RECTANGLE as String = "RoundedRectangle"
Public Const S_LBL_RND_SQUARE as String = "RoundedSquare"
Public Const S_LBL_RND_DIAMOND as String = "RoundedDiamond"
Public Const S_LBL_OVAL as String = "Oval"
Public Const S_LBL_CIRCLE as String = "Circle"